# yaml-language-server: $schema=none
name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/hunter-setlist-archive
          git restore .
          git pull origin main
          npm install --omit=dev
          export $(cat .env | xargs) && npx prisma migrate deploy
          export $(cat .env | xargs) && npx prisma generate
          export $(cat .env | xargs) && npm run build
          sleep 2
          export $(cat .env | xargs) && pm2 reload hunter-archive || (pm2 start npm --name "hunter-archive" -- start)
          pm2 save