name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/hunter-setlist-archive
          git restore .
          git pull origin main
          npm install --omit=dev
          source .env && npx prisma db push --force-reset --accept-data-loss
          source .env && psql "$DATABASE_URL" -f /root/hunter-dump.sql
          npm run build
          pm2 reload hunter-archive || pm2 start npm --name "hunter-archive" -- start